config/matching_params.yml, src/stratigraphy/main.py, src/stratigraphy/util/depthcolumn.py, src/stratigraphy/util/find_description.py, src/stratigraphy/util/geometric_line_utilities.py, src/stratigraphy/util/interval.py
**Implementation of left line splitting of blocks**
This PR contains the code and parameter to split blocks based on small indicator lines on the lefthandside of the blocks. These lines are often used when space is tight, and come in conjunction with what we call 'splitting due to vertical distances'.
Overall, **F1 improved from 86.3% to 86.7%.** The changes are mainly driven due to a few documents where larger improvements could be made.
**Document level metric changes:**
The below table contains all documents that have a change in their F1 metric. 'left_splitting' indicates the new metrics, obtained with this PR:
There are mostly improvements, but a few cases come with a lowering in the score. Sometimes it's not so clear why (typically documents that have a low score anyways). Sometimes …
=> Feat: Separate blocks by short indicator lines on the left of a block.

environment-dev.yml, src/stratigraphy/main.py, src/stratigraphy/util/geometric_line_utilities.py, src/stratigraphy/util/plot_utils.py, tests/test_geometric_line_utilities.py
Implementation of ODR regression for line merging. 
Results slightly improve.
The only document that changes is:
|    | document_name    |   F1_new |   Number Elements_new |   Number wrong elements_new |       F1 |   Number Elements |   Number wrong elements |
|---:|:-----------------|---------:|----------------------:|----------------------------:|---------:|------------------:|------------------------:|
|  0 | 699240002-bp.pdf | 0.468085 |                    27 |                          16 | 0.425532 |                27 |                      17 |
Vertical lines are still not dealt with, but the code at least throws a warning and does not do unintentional behavior.
=> ODR Regression for line merging.

src/stratigraphy/benchmark/ground_truth.py, src/stratigraphy/benchmark/score.py, src/stratigraphy/main.py, src/stratigraphy/util/depthcolumn.py, src/stratigraphy/util/depthcolumnentry.py, src/stratigraphy/util/draw.py, src/stratigraphy/util/interval.py, src/stratigraphy/util/line.py, src/stratigraphy/util/textblock.py, src/stratigraphy/util/util.py
**Content**
Previously, inference (i.e. perform_matching) was dependent on ground_truth information. Furthermore, various validation steps in form of drawing onto pdf pages was done in perform matching. This commit moves all evaluation steps to evaluate_matching.
The file predictions.json is adjusted and now contains much more information. The information is sufficient to reconstruct all drawings in the pdf pages, without the need of the python objects.
In particular, predictions.json now contains:
- information about material_description and depth_column pairs (bounding boxes & values)
- more information about the identified material description blocks (bounding boxes as well as lines)
Also comes with some refactoring of the main.py script.
Scores are not affected.
**Discussion**
Let me …
=> Refactor: Decouple inference from evaluation.

config/matching_params.yml
Descriptions such as "Kein Kernmaterial (ungestörte Probe)" should also be considered as valid material descriptions. However, previously, these were usually not correctly recognized. This is fixed by adding "Kernmaterial" to the list of keywords that are used to find the material descriptions in the document.
The change improves the output for three documents in the validation dataset: 267125307-bp.pdf, 267125308-bp.pdf and 268124336-bp.pdf. Overall, the F1 score improves from 87.7% to 87.9%.
=> add "Kernmaterial" to list of keywords for material description

.github/workflows/pre-commit.yml, .github/workflows/pytest.yml
Introduction of GitHub actions.
Two actions are defined:
1. pre-commit action: Checks whether our pre-commit hooks pass (i.e. ruff lint and ruff format)
2. pytest action: Checks whether all tests pass.
Note: As of now the pytest action is not much abstracted. We do the installation of miniforge and the execution of the test command in the same step. I did not manage to have conda work across steps as some things are not shared across steps (e.g. shell environment). Re-sourcing the bash profile in subsequent step did not help.
Note 2: It would be nice to add code coverage.
=> Add github actions

src/stratigraphy/benchmark/score.py, src/stratigraphy/extract.py, src/stratigraphy/line_detection.py, src/stratigraphy/main.py, src/stratigraphy/util/dataclasses.py, src/stratigraphy/util/draw.py
Here the discussed proposition.
I think we can extend the thought even further and include the draw_predictions earlier. That would require that we load the ground truth earlier as well. I keep this for the future as the current implementation currently already serves for discussion.
=> Refactor extraction pipeline.2

config/matching_params.yml, src/stratigraphy/benchmark/score.py, src/stratigraphy/extract.py, src/stratigraphy/util/depthcolumn.py, src/stratigraphy/util/draw.py, src/stratigraphy/util/find_depth_columns.py, src/stratigraphy/util/interval.py, tests/test_find_depth_columns.py
In this PR we:
- Added visualization whether depth interval is correct.
- Improved the depth_column recognition by weakening the noise_count criterion.
**Result**
Depth_interval_accuracy improves from 42% to 62.3% while keeping F1 score at 49.3%.
The F1 score for the Zurich dataset decreased to 87.1% from 87.9%.
For future implementation we might want to reconsider how we split the material description blocks with regards to the criterion that we expect the same number of blocks as depth intervals.
Leaving this PR for review now.
=> Improve Depth Intervals

src/stratigraphy/line_detection.py, src/stratigraphy/util/dataclasses.py, src/stratigraphy/util/geometric_line_utilities.py, src/stratigraphy/util/linesquadtree.py
Code review proposal for https://github.com/swisstopo/swissgeol-boreholes-dataextraction/pull/38
- Link multiple lines with a single point in the quad tree
- Remove the need for recursive calls of the "merge lines by quad tree" method
- Remove the need for the inefficient check for duplicate lines
I think that some unit tests for the LinesQuadTree class could be really useful, but I did not have time to implement any new tests yet. I'll leave that up to you @redur to either add some unit tests, or to accept this PR as-is already and to leave writing unit tests for later.
=> quad tree with points that have a set of line indices as data

config/matching_params.yml, src/stratigraphy/extract.py, src/stratigraphy/util/find_depth_columns.py, src/stratigraphy/util/find_description.py, src/stratigraphy/util/layer_identifier_column.py, src/stratigraphy/util/layer_index_column.py, tests/test_find_depth_columns.py
Includes functionalities to recognize material description blocks for the Geneva borehole profile layout. The code detects so called layer index columns which indicate the presence of a material description rect as well as their position marks how to split the material description rect into material blocks. Note: Some visualization code is part of this commit which should be dropped in a follow up commit.
=> Feat: Material Block recognition for Geneva Layout

src/stratigraphy/benchmark/score.py
Previously we just appended the columns with pd.concat. Now we make sure the right rows are assigned with each other, as well as do not duplicate the document_name column any more.
=> Fix duplicate column 'document_name' in document_level_metrics table.

src/stratigraphy/extract.py, src/stratigraphy/main.py, src/stratigraphy/util/duplicate_detection.py, src/stratigraphy/util/geometric_line_utilities.py, src/stratigraphy/util/plot_utils.py
The score remains unaffected (less than 0.1% improvement), the duplicate detection is now improved.
Check borehole profile A525.pdf to see the changes.
**Overall logic:**
If there is depth information for a given layer --> use that information to detect duplicates.
If there is no depth information for a given layer --> use template matching.
I argue to keep template matching in the logic, as there are borehole profiles that do not have depth columns, and many layers may not have any depth-information assigned. Especially older borehole profiles, sometimes come with a visual representation of depth information and I believe template matching is still the best way to go in that case.
=> Improve duplicate detection to use depth information

config/matching_params.yml, src/stratigraphy/main.py, src/stratigraphy/util/coordinate_extraction.py, src/stratigraphy/util/language_detection.py
PR to parametrize language in the config files.
I believe there should be nothing remaining in the code that specifies a language now. The language is completely abstracted in the matching_params.yml config file.
=> Parametrize language in language detection and coordinate extraction.

config/matching_params.yml, src/stratigraphy/extract.py, src/stratigraphy/main.py, src/stratigraphy/util/coordinate_extraction.py, src/stratigraphy/util/draw.py, src/stratigraphy/util/extract_text.py, tests/test_coordinate_extraction.py
- Separate the creation of TextLine object for a given PDF page into a separate method, that is used by both layer extraction and coordinate extraction.
- Instead of finding the coordinate key in the plain document text, find it in the TextLine objects, so that we also have the information of where it is located on the PDF page
- Instead of looking for coordinates within 100 characters of the coordinate key (in the defaut "reading order"), look for coordinates to the right and/or immediately below the coordinate key. This should be a little more robust / less dependent on they way (in which order) text is defined in the document.
- Instead of concatenating the text of all pages at the beginning of the coordinate extraction, we iterate over the pages and return on the first page where a …
=> Use TextLine objects instead of the full plain text in coordinate extraction

src/stratigraphy/util/boundarydepthcolumnvalidator.py, src/stratigraphy/util/depthcolumn.py
And here the PR to include '.80' and the like as well.
=> Improve depth entry recognition for cases such as '.80'.

src/scripts/label_studio_annotation_to_ground_truth.py, src/stratigraphy/util/predictions.py
Include metadata (i.e. coordinates) in the instantiation of prediction objects from label studio and the subsequent conversion to ground truth.
=> Update conversion from label studio to ground truth.

src/app/api/v1/endpoints/create_pngs.py, src/app/api/v1/endpoints/extract_data.py, src/app/common/aws.py, tests/test_create_pngs.py, tests/test_data_extraction_from_bbox.py
Update the API based on the new S3 specs & feedback borehole application. The API now saves the single PDF pages as PNG in the `dataextraction/` path on S3. 
Furthermore, I made one small change in the prototype of a function as the parameter naming was outdated.
=> Close #LGVISIUM-74: Update the API based on the new s3 specs & feedback

src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/groundwater/utility.py, src/stratigraphy/util/predictions.py
The idea is to make the naming of variables more consistent. (For example, ground truth JSON uses "date" while the predictions.json uses "measurement_date".)
=> Close #LGVISIUM-67: Addressed the naming issues with the date

config/matching_params.yml, src/stratigraphy/elevation/elevation_extraction.py, src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/main.py, src/stratigraphy/util/predictions.py
Combined the information from the elevation with the groundwater information. This makes it possible to infer the elevation or depth from a groundwater measurement based on the elevation information from the borehole profile. The groundwater metrics benefited quite a bit from these changes, and with this feature, we can fill in missing depth or elevation information which were required. 
During the work on this issue, I also saw that some of the information from the Groundtruth seems to be wrong. 
There are still a few false positives due to the fact that the depth of the groundwater sometimes seems to be determined against the elevation of the drilling and sometimes against the elevation of the borehole. It is not exactly clear to me what the difference is and how we can mitigate this.
=> Close #LGVISIUM-70: Combine groundwater information with elevation to determine groundwater depth

.env.template, .vscode/settings.json, README.md, src/app/api/v1/endpoints/create_pngs.py, src/app/common/aws.py, src/app/common/config.py, tests/conftest.py, tests/test_create_pngs.py, tests/test_data_extraction_from_bbox.py
I implemented the changes required by test users to make it possible to use environment variables to specify the AWS credentials to the API. The credentials can also be specified in an `.env` file now. 
The `create_pngs` path also now directly returns the file path within the S3 bucket without specifying the bucket URL.
=> Close #LGVISIUM-84: Added possibility to pass the AWS Credentials in an .env file or as environment variables

src/stratigraphy/data_extractor/data_extractor.py, src/stratigraphy/groundwater/utility.py, src/stratigraphy/metadata/elevation_extraction.py, src/stratigraphy/util/util.py
Started to sort vertically the different text lines matched around the matched keyword. By sorting, it was possible to test which was the closest to the keyword first and thus reduce the number of false positives or errors in elevation and groundwater detection. 
@stijnvermeeren-swisstopo In today's stand-up, we discussed the possibility of vertically and horizontally sorting the text. Currently, all the issues I found are solved with this code in combination with the improvements you made in the OCR processing. However, if you wish, I can also try this technique. 
The metrics from the `main` branch are in silent-quail-641, and the performance of this branch is `ambitious-mule-939`
=> Close #LGVISIUM-77: Wrong elevation value selected within bounding box

src/app/api/v1/endpoints/create_pngs.py, src/app/common/schemas.py, tests/test_create_pngs.py
As the API is returning the key within the S3 bucket where the created PNG file is stored, it felt necessary to adapt the naming in the API response as well to avoid any type of confusion regarding what is returned.
=> Close #LGVISIUM-94: Renaming of the output from create png api path

.github/workflows/pipeline_run.yml, .github/workflows/pre-commit.yml, .github/workflows/pytest.yml, pyproject.toml, src/stratigraphy/annotations/draw.py, src/stratigraphy/data_extractor/data_extractor.py, src/stratigraphy/depths_materials_column_pairs/depths_materials_column_pairs.py, src/stratigraphy/evaluation/groundwater_evaluator.py, src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/groundwater/gw_illustration_template_matching.py, src/stratigraphy/metadata/coordinate_extraction.py, src/stratigraphy/metadata/elevation_extraction.py, src/stratigraphy/util/predictions.py, tests/test_predictions.py
A generic `FeatureOnPage` class that can be reused for groundwater, elevation, coordinates... instead of requiring separate classes `GroundwaterOnPage`, `ElevationOnPage`, `CoordinatesOnPage` etc.    
Upgrade to Python 3.11 in order to be able to use `from typing import Self`.
=> LGVISIUM-80: review proposal Stijn

src/app/api/v1/endpoints/extract_data.py, src/stratigraphy/data_extractor/data_extractor.py, src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/groundwater/gw_illustration_template_matching.py, src/stratigraphy/groundwater/utility.py, src/stratigraphy/main.py, src/stratigraphy/metadata/coordinate_extraction.py, src/stratigraphy/metadata/elevation_extraction.py, src/stratigraphy/metadata/metadata.py, tests/test_coordinate_extraction.py, tests/test_data_extraction_from_bbox.py
Changes done:
- In the extract_depth function, the ValueError handling has been incorporated, and the matched pattern are now more specific to groundwater depth. This change reduced the number of ValueErrors encountered during float conversion, which previously caused the process to exit the loop prematurely. However, this refinement has led to an increase in false positives.
- To reduce these false positives, the logic for finding groundwater information has been changed. Groundwater search is now directly tied to the material description bounding box, meaning groundwater data is only search for in areas associated with material descriptions. This adjustment reduces unnecessary searches on pages without material descriptions and ensures groundwater extraction is more contextually related …
=> Lgvisium 100/extract depth value error handling

src/stratigraphy/depths_materials_column_pairs/material_description_rect_with_sidebar.py, src/stratigraphy/sidebar/a_above_b_sidebar.py, src/stratigraphy/sidebar/a_above_b_sidebar_extractor.py, src/stratigraphy/sidebar/a_above_b_sidebar_validator.py, tests/test_aabovebsidebar.py
- More robust detection / exclusion of arithmetic progressions (or very similar sequences) as depth values.
- When computing the score of a "(material description rect + sidebar) match", use the noise count relative to the total number of depth entries, because longer sidebars are likely to have more noise anyway.
=> LGVISIUM-96: more robust depth values

pyproject.toml, src/stratigraphy/main.py
This change allows us to track the current git branch as well as the last commit (message + id) in MLFlow.
This could be helpful in tracking which experiment run corresponds to which state of the code, reducing the need to recall this from memory or to write manually a description for each run.
Also sets the default experiment name to "Boreholes data extraction" (more accurate than the previous "Boreholes Stratigraphy")
=> Tag git branch and last commit in MLFlow

src/stratigraphy/sidebar/a_above_b_sidebar.py, src/stratigraphy/sidebar/a_above_b_sidebar_extractor.py, src/stratigraphy/sidebar/a_above_b_sidebar_validator.py, tests/test_aabovebsidebar.py
Follow-up to [Pull#111](https://github.com/swisstopo/swissgeol-boreholes-dataextraction/pull/111):
- Moved OCR corrections to the make_ascending() function, eliminating the need for OCR corrections in reduce_until_valid().
- Added correction for entries by a factor of 10 where possible within make_ascending().
- Optimized is_strictly_increasing() and pearson_correlation_coef() to improve computation time.
These changes reduced processing time for Bearsol.pdf from 12 minutes to 5.4 minutes.
The F1 score for Zurich is now 0.8902 (previously 0.8911), with the slight drop due to a single bore profile. In one entry, the digit 1 was misrecognized as 4, and the decimal point was not detected by the OCR. The current correction method only adjusts for either the decimal point or the misrecognized …
=> Lgd 564/improve ocr mistake handling

README.md, pyproject.toml, src/app/common/config.py
Description:
While setting up the project, I ran into a few small issues that might affect other as well. I’ve updated the README.md with additional setup instructions. Additionally, I made minor modifications to config.py because it wasn't correctly sourcing the environment variables.
=> Improve setup documentation

example/example_gw_groundtruth.json, example/example_layers_groundtruth.json, src/stratigraphy/annotations/draw.py, src/stratigraphy/benchmark/score.py, src/stratigraphy/evaluation/evaluation_dataclasses.py, src/stratigraphy/evaluation/groundwater_evaluator.py, src/stratigraphy/evaluation/layer_evaluator.py, src/stratigraphy/evaluation/metadata_evaluator.py, src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/main.py, src/stratigraphy/util/borehole_predictions.py, src/stratigraphy/util/file_predictions.py, src/stratigraphy/util/overall_file_predictions.py, src/stratigraphy/util/predictions.py, tests/test_groundwater.py, tests/test_predictions.py
@TicaGit something like this is what I had in mind when reviewing the other PR.
It still needs some cleaning up, and I'm not entirely happy with the amount of "wrapper dataclasses" that I had to define for this, but overall the logic seems much cleaner / easier to follow like this.
Unit tests don't work yet. The main problem there is that we have unit tests that seem to test two things at once: the matching of extracted data with ground truth data, as well as the evaluation of the individual attributes. We should probably split that into two.
In the evaluation, extracted data without a corresponding ground truth now always counts as false positives. This decreases the scores a little bit, also for Geoquat, as there are a few examples where one borehole in the ground truth is extracted in …
=> refactor predictions - ground truth associations

pyproject.toml, src/app/api/v1/endpoints/create_pngs.py, src/stratigraphy/annotations/draw.py
Ensure the cache is clear before creating a visualization of some PDF. Otherwise, it can occur that certain cached objects from one PDF will break the visualization of another PDF. (See also https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1935.)
E.g. this error occurs with Nagra PDFs when first processing `Dossier III_Appendix A_BOZ1-1_Lithostratigraphy_1_2500_0000-1037.39.pdf` and then `Dossier III_Appendix A_BUL1-1_Lithostratigraphy_1_2500_0000-1370.pdf`. The representation of the first (quaternary) layer will then look blue instead of black-on-white.
I will report this as an issue to the PyMuPDF library. -> https://github.com/pymupdf/PyMuPDF/issues/4388
=> Workaround for issue with cache contamination in pymupdf

pyproject.toml, src/app/common/schemas.py
This PR addresses issue #127. It removes deprecation warnings, that are especially appearing when running pytest.
**Pydantic 2.x Compatibility**
The code has been updated to follow the new Pydantic 2.x format:
- Replaced the old Config class with model_config = ConfigDict(...) for setting model options.
- Moved example values from Field(...) into json_schema_extra inside the ConfigDict.
**Ignoring Warnings from Third-Party Libraries**
Some deprecation warnings come from external libraries (botocore and SWIG). Since we can’t fix these in our code, they are now ignored during test runs to keep the output clean.
=> Fix/issue 127/pydantic depr warnings

src/stratigraphy/depths_materials_column_pairs/bounding_boxes.py, src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/groundwater/gw_illustration_template_matching.py, src/stratigraphy/groundwater/utility.py, src/stratigraphy/main.py, src/stratigraphy/metadata/elevation_extraction.py, src/stratigraphy/util/borehole_predictions.py, src/stratigraphy/util/predictions.py, tests/test_groundwater.py
Summary
This PR primarily addresses issue #151: Unreliable Assignment of Extracted Data to Borehole Profiles. Since this issue is related to groundwater data extraction, the PR also resolves issue #142 and its duplicate #118.
**Improvements in Data Assignment ("Smart Merge")**
- Borehole elements (elevation, coordinates, groundwater) are now correctly assigned to their respective borehole layers based on their position on the page, rather than relying on extraction order.
- BoreholeInDocument now stores all extracted groundwater data, but no assignments occur during extraction. Instead, all assignments happen in BoreholeListBuilder.build(), ensuring correctness.
- Elevation is no longer passed during the extraction phase. Missing groundwater attributes (depth, elevation) are assigned …
=> Feat/issue 151/multiple borehole smart merge

config/matching_params.yml, src/stratigraphy/depth/interval.py, src/stratigraphy/sidebar/a_above_b_sidebar.py
Resolves #146
The initial issue was not reproducible, and the problems on Nagra were mostly related to those parasite depths that does not belong to any material descriptions (see: https://github.com/swisstopo/swissgeol-boreholes-dataextraction/issues/146#issuecomment-2786898212).
I remove the magic number and performed a quick parameter search, best value seems to be 10. (see https://github.com/swisstopo/swissgeol-boreholes-dataextraction/issues/146#issuecomment-2789501775)
=> Fix/issue 146/false positive exact matches

config/matching_params.yml, src/app/api/v1/endpoints/extract_data.py, src/stratigraphy/data_extractor/data_extractor.py, src/stratigraphy/groundwater/groundwater_extraction.py, src/stratigraphy/main.py, src/stratigraphy/metadata/language_detection.py, src/stratigraphy/metadata/metadata.py, tests/test_coordinate_extraction.py
Resolves #147
Sort the keywords by language in the Yaml file. This is cleanier, and also avoids some false positives.
For example, false positives removed in geoquat/validation from A289 (Kappe not matched as nappe anymore),  1007 (GW not matched, as documents is in french), 2536 (GW not matched, as document is in french).
=> Fix/issue 147/keywords by language

config/matching_params.yml, src/stratigraphy/extract.py, src/stratigraphy/sidebar/layer_identifier_sidebar.py, src/stratigraphy/sidebar/layer_identifier_sidebar_extractor.py, tests/test_layer_identifier_sidebar.py
Resolves #119 
This PR adds a check to LayerIdentifierSidebar that rejects sidebars which do not follow a logical progression (e.g., 2 < 3a < 3b < 5 is valid). This check is necessary to prevent the columns of letter "m)" (indicating meters) in the file deepwell Arsch from being mistakenly identified as a sidebar.
Additionally, it rejects some sidebars in the files 12318, 5878, and 9394 in geoquat. All of these rejections are correct and result in slight improvements to the metrics. No other changes have been made for Zurich, deepwell, or Nagra.
The try-except block is used to handle cases where letters are mistakenly extracted as numbers, which would cause crashes during comparison (in B147 and 680). These cases do not impact the desired behavior.
This PR also changes the ordering of …
=> Fix/issue 119/layer identifier sidbar fix

config/matching_params.yml, src/extraction/annotations/draw.py, src/extraction/features/extract.py
This issue was not reproducible anymore, the overlapping inside deepwell 3EK5LEG800_bp_19940601_Arsch93-18.pdf was already resolved by PR#174, and no similar problems existed in the datasets. I implemented a quick solution anyway, as this problem could appear in some other pdf unseen yet.
Some additional checks are applied to filter out material descriptions with sidebars before validating them as actual boreholes.
The first check removes any pair that contains no depth information (i.e.all depth values are None). This affects the following files:
GeoQuat
- False positives removed (good): 14225.pdf, A11406.pdf, 1488.pdf, 14273.pdf
- True positive removed (bad): A1304.pdf: According to the ground truth, this file contains three boreholes. One is correctly detected. The second borehole is …
=> check for intersections between material descriptions and sidebars

src/classification/utils/data_loader.py, src/extraction/evaluation/benchmark/ground_truth.py
Ground truth data now can have NoneType as material description in contrast to solely string as previously. Thus the small adjustment in the loading of the ground truth is needed to handle NoneType inputs in Layers.
=> handle missing values in ground_truth layers.

config/matching_params.yml, src/extraction/features/extract.py
resolves #211 
This PR aims to address mismatches in layer extraction by refining the logic used in the extraction process.
In _get_interval_block_pairs, the filtering for boreholes with less than 2 layers was removed, as this check was not deleting the correct bounding box.
In process_page, boreholes are now filtered based on the number of layers using the min_num_layers parameter.
=> layers-bb-mismatch

config/bedrock/bedrock_config_lithology.yml, config/bedrock/bedrock_config_uscs.yml, src/scripts/get_files.py
Fixes issues with https://github.com/swisstopo/swissgeol-boreholes-dataextraction/pull/234 where incorrect config file references where supplied to the AWS Bedrock classifier pipeline.
=> Fixes to the bedrock config files for USCS and Lithology classification.

src/extraction/features/utils/geometry/geometric_line_utilities.py, tests/test_geometric_line_utilities.py
Follow-up for https://github.com/swisstopo/swissgeol-boreholes-dataextraction/pull/237
Removes the method `is_point_on_line` that was no longer used in the code (except for unit tests).
The test cases have been preserved (in slightly adapted form) as unit tests for the new method `is_point_near_line`.
=> #230: cleanup unused method 

.env.template, .github/workflows/pre-release.yml, Dockerfile, pyproject.toml, src/classification/classifiers/aws_bedrock_classifier.py
This PR modifies the Dockerfile to significantly reduce image size and improve build performance.
Changes:
By replacing the pip-tools installation approach (pip-compile + pip-sync) with a simpler  `pip install --no-cache-dir .`, I was able to reduce the image size.
Additionally, I tried to remove the heavy packages: transformers, datasets, torch, accelerate
Results:
With pip-tools:
~10 GB image on GitHub Actions, ~3 GB locally
With pip install .:
~6.37 GB on GitHub, ~2.22 GB locally
After removing heavy packages:
~714 MB on GitHub, ~1.12 GB locally
Trade-offs:
The image is much smaller and builds faster. However, we lose some of the reproducibility benefits from pip-sync, such as precise version locking and hash checking.
I'm not sure if this trade-off is good enough or if we should keep …
=> Reduce docker image size

src/classification/utils/data_formatter.py
The reference resolution function was matching against the second extracted depths instead of the first, this led to missalignment between the prediction files and the ground truth matching.
=> fix to match against the first depth and not the second one

src/app/common/schemas.py, src/extraction/annotations/draw.py, src/extraction/features/extract.py, src/extraction/features/metadata/coordinate_extraction.py, src/extraction/features/predictions/predictions.py, src/extraction/features/utils/data_extractor.py, src/extraction/features/utils/geometry/geometry_dataclasses.py, src/extraction/features/utils/text/textblock.py, src/extraction/features/utils/text/textline.py, tests/test_coordinate_extraction.py
Resolve #228
This PR introduces a unified RectWithPage object that encapsulates both a rectangle and its associated page number.
To simplify access, classes that hold a RectWithPage now inherit from a new RectWithPageMixin class, which exposes .rect and .page_number as @propertys. This allows continued use of .rect and .page_number directly on the object, without needing to access .rect_with_page.rect or .rect_with_page.page_number.
The PR also resolves the fallback page issue by providing the page_number of the `Layer` object (taken from its `FeatureOnPage[MaterialDescription]` attribute), which is, by construction, the same as the one in the `LayerDepthsEntry` object.
=> Feat/issue 228/page rect object

src/extraction/features/stratigraphy/sidebar/classes/a_above_b_sidebar.py, src/extraction/features/utils/geometry/geometry_dataclasses.py, src/extraction/features/utils/geometry/util.py, tests/test_aabovebsidebar.py, tests/test_dataclasses.py
Get rid of some warning messages from numpy, e.g. when processing Geoquat file A11276.pdf .
The fact that we had some lines of length 0, comes from the rounding of line coordinates in the `line_from_array` method, which I have now removed.
The more accurate line coordinates (floats instead of integers) lead to minor changes in the metrics.
For Zürich, we have minor improvements for 267125339-bp.pdf, 677250019-bp.pdf and 687250019-bp.pdf and a minor drop in accuracy for 680244002-bp.pdf (which is a scan of a boreprofile on [graph paper](https://en.wikipedia.org/wiki/Graph_paper), which understandably is confusing the line detection algorithms, since we've never optimized for this case).
For GeoQuat, we have a minor improvement for A8415.pdf and a minor drop in accuracy for A8236.pdf (where …
=> improve handling of edge cases in geometry methods

config/classification_params.yml, src/classification/utils/data_formatter.py, tests/classification/test_data_formatter.py
Resolves #254 
This PR simplifies the reference resolution logic in the data formatter by consolidating regex patterns and fixing incorrect reference handling. The changes aim to make the code more maintainable while correcting bugs in depth reference extraction.
- Consolidates multiple regex operations into a single comprehensive pattern
- Fixes incorrect handling of some depth references (like matching the word Dolomites, or matching depths appearing in the middle of the description).
- Simplifies the string replacement logic for resolved references
=> simplify matching with regex, correct wrong references

pyproject.toml
Resolves #260
This PR upgrades the version of `numpy`, along with several other libraries.
All updated versions are now pinned in pyproject.toml to ensure reproducibility and alignment across environments.
=> upgrade numpy to v2.x, pin dependencies

src/extraction/features/extract.py, src/extraction/features/stratigraphy/interval/interval.py, tests/test_interval_block_pair.py
Resolves #266
This PR implements depth stripping functionality to remove depth information from the beginning of text lines in stratigraphic interval data. The implementation adds a get_clean_block() method to IntervalBlockPair that uses regex patterns to identify and remove depth patterns from text blocks.
=> implement depths striping from beginning of the line

src/extraction/features/utils/text/extract_text.py, src/extraction/features/utils/text/stemmer.py, src/extraction/features/utils/text/textline.py, tests/test_textline_matching.py
Resolves #273 
This PR refactors the text processing functionality by moving the stemming and compound word–splitting logic out of the TextLine class into a dedicated stemmer module. By centralizing stemming in a separate module, we can create a single persistent stemmer instance per language (singleton pattern) and reuse it throughout the program’s execution.
In addition, this refactor improves the overall organization of the TextLine class and adds new tests to increase coverage of both the compound splitter and the stemmer.
=> Refactor/issue 273/stemmer textline
